name: CGO Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib
    - name: Build Linux AMD64
      run: |
        go mod download
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ga4admin-linux-amd64 ./cmd/ga4admin/main.go
    - name: Build Linux ARM64
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu
        CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o ga4admin-linux-arm64 ./cmd/ga4admin/main.go
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-binaries
        path: |
          ga4admin-linux-amd64
          ga4admin-linux-arm64

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Build macOS
      run: |
        go mod download
        CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o ga4admin-darwin-amd64 ./cmd/ga4admin/main.go
        CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o ga4admin-darwin-arm64 ./cmd/ga4admin/main.go
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-binaries
        path: |
          ga4admin-darwin-amd64
          ga4admin-darwin-arm64

  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux binaries
      uses: actions/download-artifact@v3
      with:
        name: linux-binaries
    - name: Download macOS binaries
      uses: actions/download-artifact@v3
      with:
        name: macos-binaries
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ga4admin-linux-amd64
          ga4admin-linux-arm64
          ga4admin-darwin-amd64
          ga4admin-darwin-arm64
        generate_release_notes: true