name: Debug Build

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Check Go version
      run: go version

    - name: List files
      run: ls -la

    - name: Check go.mod
      run: cat go.mod

    - name: Try go mod tidy
      run: go mod tidy

    - name: Try simple build
      run: go build cmd/ga4admin/main.go

    - name: List built files
      run: ls -la