name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod tidy

    - name: Build for macOS (AMD64)
      run: |
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ga4admin-darwin-amd64 cmd/ga4admin/main.go

    - name: Build for macOS (ARM64)
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o ga4admin-darwin-arm64 cmd/ga4admin/main.go

    - name: Build for Linux (AMD64)
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ga4admin-linux-amd64 cmd/ga4admin/main.go

    - name: Build for Linux (ARM64)
      run: |
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o ga4admin-linux-arm64 cmd/ga4admin/main.go

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ga4admin-darwin-amd64
          ga4admin-darwin-arm64
          ga4admin-linux-amd64
          ga4admin-linux-arm64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}