name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
            name: ga4admin-darwin-amd64
          - os: darwin
            arch: arm64  
            name: ga4admin-darwin-arm64
          - os: linux
            arch: amd64
            name: ga4admin-linux-amd64
          - os: linux
            arch: arm64
            name: ga4admin-linux-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build binary
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -o ${{ matrix.name }} cmd/ga4admin/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ga4admin-darwin-amd64/ga4admin-darwin-amd64
          ga4admin-darwin-arm64/ga4admin-darwin-arm64
          ga4admin-linux-amd64/ga4admin-linux-amd64
          ga4admin-linux-arm64/ga4admin-linux-arm64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}