name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            name: ga4admin-linux-amd64
          - os: macos-13  # Intel runner
            goos: darwin
            goarch: amd64
            name: ga4admin-darwin-amd64
          - os: macos-14  # Apple Silicon runner
            goos: darwin
            goarch: arm64
            name: ga4admin-darwin-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Linux build tools
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Download dependencies
      run: go mod download

    - name: Build binary with CGO
      run: |
        CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
        go build -ldflags="-s -w" -o ${{ matrix.name }} ./cmd/ga4admin/main.go

    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.name }}
        generate_release_notes: true